# Generated by Django 3.1 on 2020-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jassoseol',
            new_name='Jasoseol',
        ),
    ]
